[package]
name = "rust_csv_googlemap_splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
futures = "0.3.30"
indicatif = "0.17.8"
rayon = "1.10.0"
tokio = { version = "1.37.0", features = ["full"] }
